version: '3'
services:
  planner:
    image: vimagick/timeoff-management:latest
    container_name: omundopula_planner
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
